version: "3.7"

services:
  middle:
    image: docker.pkg.github.com/wafflestudio/snuday-server/server-image
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=mysql
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    working_dir: /root
    command: python manage.py runsslserver --certificate django.crt --key django.key 0.0.0.0:8000
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
