# Generated by Django 3.1.6 on 2021-02-07 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channel', '0002_auto_20210206_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userchannel',
            name='is_manager',
        ),
        migrations.AlterField(
            model_name='channel',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribing_channels', through='channel.UserChannel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ManagerChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channel.channel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='managers',
            field=models.ManyToManyField(related_name='managing_channels', through='channel.ManagerChannel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='managerchannel',
            constraint=models.UniqueConstraint(fields=('channel', 'user'), name='manager_relation_should_be_unique_together'),
        ),
    ]
