# Generated by Django 3.1.6 on 2021-02-28 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channel', '0003_auto_20210207_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwaiterChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channel.channel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='awaiters',
            field=models.ManyToManyField(blank=True, related_name='waiting_channels', through='channel.AwaiterChannel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='awaiterchannel',
            constraint=models.UniqueConstraint(fields=('channel', 'user'), name='subscription_waiting_should_be_unique'),
        ),
    ]
