# Generated by Django 3.1.6 on 2022-03-26 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("channel", "0007_auto_20220324_2013"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ManagerChannel",
        ),
    ]
