# Generated by Django 3.1.6 on 2022-07-24 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0008_delete_managerchannel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchannel',
            name='color',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
