# Generated by Django 3.1.6 on 2021-02-19 01:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channel', '0003_auto_20210207_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contents', models.CharField(max_length=100)),
                ('has_data', models.BooleanField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('channel', models.ForeignKey(db_column='channel_id', on_delete=django.db.models.deletion.CASCADE, related_name='event_channel', to='channel.channel')),
                ('writer', models.ForeignKey(db_column='writer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_writer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
