# Generated by Django 3.1.6 on 2021-03-03 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0002_auto_20210219_1057"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="due_date",
            new_name="due_date",
        ),
    ]
