# Generated by Django 3.1.6 on 2021-03-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0005_auto_20210303_2348"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="contents",
            new_name="title",
        ),
        migrations.AddField(
            model_name="event",
            name="memo",
            field=models.TextField(null=True),
        ),
    ]
