# Generated by Django 3.1.6 on 2021-03-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0006_auto_20210304_0057"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="due_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="start_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="due_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="event",
            name="start_date",
            field=models.DateField(),
        ),
    ]
