# Generated by Django 3.1.6 on 2021-03-31 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0008_auto_20210330_0151"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="due_date",
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="start_date",
            field=models.DateField(blank=True),
        ),
    ]
