# Generated by Django 3.1.6 on 2021-03-31 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_auto_20210206_0731"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_prefix", models.CharField(max_length=100, unique=True)),
                ("verification_code", models.CharField(max_length=6)),
                ("is_verified", models.BooleanField(default=False)),
            ],
        ),
    ]
