# Generated by Django 3.1.6 on 2021-02-07 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='user',
        ),
        migrations.AddField(
            model_name='notice',
            name='writer',
            field=models.ForeignKey(db_column='writer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='writer', to=settings.AUTH_USER_MODEL),
        ),
    ]
